world-wide-techies/P2PCoder

- README.md
- Adding name to README
- Closes # https://github.com/annonymousauthority/P2PCoder/issues/12
- Related Issues: (enter ticket numbers here)
> adding name to README

- README.md
Add name to readme name section
> Remi update readme with name

- src/composables/peerIdGenerator.js
This PR resolves #7 
Write a function that generates 10 characters peer id
> 10-character peer ID generator

- src/composables/accountVerifiedFunc.js
- src/composables/acctVerfiedFunc.js
Fixes #4 
Implemented a function to check if the user account is verified
> function to check if user account is verified

- src/composables/emailPasswordValidator.js
> Created an email and password validator function

- src/components/onboarding_comp.js
- Created the onboarding view component
- Fixes #38
> created the onboarding view component

- src/components/onboardingHeader.js
This component takes in h1 and p props.
> Created onboarding header component

- README.md
Added my name to readme
- Closes #50 
- Related Issues: (enter ticket numbers here)
(In this section, describe how to QA/review your PR. Feel free to use screenshots and/or short videos)
> docs: upadate readme with my name

- src/components/onboardingHeader.js
Added "dark:text-violet-200" in the h1 tag and "dark:text-neutral-200" in the p tag.
> Implemented dark theme in onboardingHeader component

- src/components/onboarding_comp.js
> implemented dark mode in onboarding component

- src/app/page.js
- src/app/tests/page.js
- src/components/navbar_components/editorNavbar_comp.js
- src/components/navbar_components/sidebar_components/sideBarNavControl.js
- src/components/navbar_components/sidebar_components/sideBottomNavControl.js
- src/components/navbar_components/sidebar_components/sideTopNavControl.js
- src/components/navbar_components/tabbar_components/tabBarControls_comp.js
- src/components/navbar_components/tabbar_components/tabBarItem.js
Created the main page route, added navigator components.
> update on main Editor Page and navigators

- src/components/VerificationOverlay.js
> Updated icon and dark theme on verification overlay

- src/components/userLogin_comp.js
added icons to the login component
> added icons to the login component

- src/app/page.js
**This PR resolves #76 **
This PR fix the issue of "barItems" stored in local storage not persisting on page reloads.
> 76 "barItems" stored in local storage not persisting on page reloads

- package-lock.json
- package.json
- src/app/page.js
- src/components/modal.js
- src/components/navbar_components/sidebar_components/sideBottomNavControl.js
- src/components/onboarding_comp.js
- src/components/signup_comp.js
- src/components/userLogin_comp.js
- src/components/welcome_comp.js
> Created Modal Routing.

- src/components/signup_comp.js
- src/composables/emailPasswordValidator.js
- src/composables/signupFormValidation.js
Bringing Signup / Login Validations back in 
Closes #123
> Signup / Login Form Validation

- .gitignore
- next.config.js
- package-lock.json
- package.json
- src/components/codingEditor.js
> update on coding Editor

- src/components/signup_comp.js
- src/components/userLogin_comp.js
- src/composables/authGithubSigninPopup.js
- src/composables/authGoogleSigninPoppup.js
`signupWithGoogle` and `signUpWithGithub` Buttons can now trigger each function assigned to them without triggering a reload on the page.
> Integrate signup with Google

- development/.babelrc
- development/package-lock.json
- development/package.json
Fixed the bug experienced by babel
> update on babel and font errors. updated packages

- development/src/app/page.js
- development/src/components/navbar_components/editorNavbar_comp.js
- development/src/components/navbar_components/sidebar_components/sideBottomNavControl.js
- development/src/composables/verifySignedIn.js
> show buttons based on auth state

- development/src/app/page.js
- development/src/components/codingEditor.js
- development/src/composables/tabContext.js
> codes persist upon refresh and unique to each tab

- development/src/components/VerificationOverlay.js
- development/src/components/signup_comp.js
- development/src/composables/authSignupFunction.js
- development/src/composables/signupFormValidation.js
- Updates the Form Validation to catch whitespace in input fields
- pushing users and their information to the 'CODERS' database
-  Email Verification function is in this PR but needs onboarding to be merged to connect
- Adding a functional close button to form
- Closes #173
> Taylor - Updating Signup Form Functionality

- development/src/components/PeerOverlay_comp.js
- development/src/components/joinSession_Comp.js
- development/src/components/signup_comp.js
- development/src/components/userLogin_comp.js
- #214 
Integrated `error modal` to replace toastify error in `session_comp.js`
`this resolves toastify is not defined error`
> Resolve Toastify Error

- development/src/app/layout.js
- development/src/app/page.js
- development/src/components/PeerOverlay_comp.js
- development/src/components/peerId_comp.js
- development/src/components/session_comp.js
- development/src/components/signup_comp.js
- development/src/components/userLogin_comp.js
- development/src/components/welcome_comp.js
- development/src/composables/dbService.js
- development/src/composables/sessionContext.js
- package-lock.json
This PR Closes 
- #216 
- #217 
- Integrated the PeerId Modal with Create Session Modal.
- Bind session component with Database 
- Implemented a functionality to route user to code editor page on successful session creation
> Remi enhancement session component integration

- development/package.json
> update on package.json

- development/src/components/PeerOverlay_comp.js
- development/src/components/VerificationOverlay.js
- development/src/components/navbar_components/sidebar_components/sideBottomNavControl.js
- development/src/components/openTabModal_comp.js
- development/src/composables/signOutFunction.js
- development/src/composables/verifySignedIn.js
Signed in User can now have access to session and Usigned user cannot.
> Fixed unauthenticated user access to collab session

- development/src/components/PeerOverlay_comp.js
- development/src/components/codingEditor.js
- development/src/components/collab_comp.js
- development/src/components/joinSession_Comp.js
- development/src/components/peerId_comp.js
- development/src/components/webcam_comp.js
- development/src/composables/dbService.js
> Feat/Enable Coder & Collaborator's display name

- development/src/components/PeerOverlay_comp.js
- package-lock.json
Description of what this Pull Request does
The correct tab title shows when a new session is created
Related Tickets & Documents
Closes #232 
QA Instructions, Screenshots, Recordings
> correct tab title on session creation

- development/src/app/page.js
- development/src/components/VerificationOverlay.js
- development/src/components/VerificationSuccessful_comp.js
- development/src/components/changeEmailOverlay_comp.js
- development/src/components/signup_comp.js
- development/src/components/userLogin_comp.js
- development/src/composables/authSignupFunction.js
- development/src/composables/userLoginFunction.js
- Signs a user up via Signup Form, the user's information is sent to Firebase but they are unable to proceed unless they verify their email
- Creates a "Change Email" Component, and routes the users to the component when they push "change email". From there the user proceeds to verify their email, leading them to verification successful, where they can click the login button to log in to their account. 
- Catches errors if the email is already used in the "Change email" 
- Restricted users from signing in if their emails haven't been verified
- Closes #230 
Normal Onboarding Flow
Changed Email Onboarding Flow
Change Email Error 
Unverified email
> Taylor - Signup Onboarding Flow

- development/src/app/page.js
- development/src/components/collab_comp.js
- development/src/components/joinSession_Comp.js
- development/src/components/peerId_comp.js
- development/src/composables/tabContext.js
> added `isCollab` property to tabItem

- development/src/components/signup_comp.js
> bug fix on create account close function

- development/src/components/navbar_components/editorNavbar_comp.js
- development/src/components/navbar_components/sidebar_components/sideBottomNavControl.js
- development/src/components/onboarding_comp.js
- development/src/components/signup_comp.js
- development/src/components/userLogin_comp.js
- development/src/composables/authGithubSigninPopup.js
- development/src/composables/authGoogleSigninPoppup.js
- development/src/composables/signOutFunction.js
- Fixed sign in routing on success 
- Fixed sign out incorrect functionality
> Fix random bugs 

- development/src/components/signup_comp.js
- development/src/components/userLogin_comp.js
- development/src/components/welcome_comp.js
- development/src/composables/userLoginFunction.js
- development/src/composables/verifySignedIn.js
- Restricting users from accessing the Collab page without creating an account and/or logging in without the correct password
- Correcting the Firebase errors with custom messages
- Routing the Login Modal to the Welcome Page
- Closes #239
> Taylor - fixing bugs on Signin / Login 
